### ISSUE TITLE
{{page.content}} not evaluating the {{VARIABLE}} tags from the page into the index.html

### ISSUE THREAD

**Issue by sidpagariya** [andrewbanchich/dimension-jekyll-theme#2]
Hello, when I make a page, say `p5.md`, and in there, there is a `{{site.email}}` tag, when I build the site, the index.html, when evaluating the `#p5` section, still shows `{{site.email}}` and does not evaluate that variable...
Could you please help me out with this issue? I am not sure how we could fix the rendering of the pages properly...

Thanks!

**Comment by andrewbanchich** [comment]
Is there a repo I can take a look at?

**Comment by sidpagariya** [comment]
You can take a look at files from https://github.com/dragonphysics/dragonphysics.github.io/tree/3a93853d53c730a856223ae848c842e929cd5147
and p5.md has a {{site.email}} which doesn't get processed...

Thanks, once again!

**Comment by andrewbanchich** [comment]
It looks like it's processed to me. Looking at the source code of the site it shows in the form element.

**Comment by sidpagariya** [comment]
Well, I have it replaced with the actual email id in the latest commit, but it didn't seem to render if you download from master one commit earlier...

**Comment by sidpagariya** [comment]
If you take a look at https://github.com/dragonphysics/dragonphysics.github.io/archive/3a93853d53c730a856223ae848c842e929cd5147.zip and then compile/build it, the form POST url in index.html isn't rendered, while p5.html is rendered properly...

Thanks!

**Comment by andrewbanchich** [comment]
I'm not sure... I tried downloading my Forty repo just now and it works without issues when I run `jekyll serve`. When I pull your repo and run it, it give me ``block in materialize': Could not find public_suffix-2.0.5 in any of the sources (Bundler::GemNotFound)` and doesn't work. I also installed the `public_suffix` gem but it still gives me the same issue.

Could you try updating everything and see if it works for you? Seeing that it works with GitHub/GitLab Pages online, I'm guessing it's an issue with your local environment, but I could be wrong.
