### ISSUE TITLE
empty button

### ISSUE THREAD

**Issue by charlesrocket** [andrewbanchich/dimension-jekyll-theme#4]
live deployment builds extra button on the right, `jekyll` exclude not helping. i guess don't have java skills to debug

**Comment by andrewbanchich** [comment]
This should be resolved now. GitHub Pages has an odd bug where its build process causes Jekyll to think there is an extra page with doesn't exist. GitLab Pages, however, wasn't affected by this.

Thanks for mentioning it!

**Comment by charlesrocket** [comment]
looks like its still parsing extra spaces for `/` items on current jekyll environment

**Comment by andrewbanchich** [comment]
@charlesrocket Yes, that's the logic I built in so that you can just add more root level pages and it will add them to the menu automatically.
